# Generated by Django 6.0.3 on 2026-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_full_name_alter_profile_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
