# Generated by Django 6.0.3 on 2026-07-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_profile_image_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
