# Generated by Django 6.0.3 on 2026-06-17 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], default='fresher', max_length=20)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('current_role', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('notice_period', models.CharField(choices=[('immediate', 'Immediate'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], default='immediate', max_length=20)),
                ('certifications', models.TextField(blank=True, help_text='Comma separated certifications')),
                ('projects', models.TextField(blank=True, help_text='Project details')),
                ('languages_known', models.CharField(blank=True, help_text='Comma separated languages', max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
